# Generated by Django 2.1 on 2018-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contract_description', models.CharField(max_length=250)),
                ('contract_location', models.CharField(max_length=100)),
                ('contract_salary', models.IntegerField()),
                ('contract_recruiter', models.CharField(max_length=250)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_telephone', models.CharField(max_length=11)),
                ('featured_contract', models.BooleanField(default=False)),
            ],
        ),
    ]
