# Generated by Django 2.1 on 2019-01-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_created_by',
            new_name='author',
        ),
    ]
