# Generated by Django 2.1 on 2018-12-07 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_salary',
            new_name='contract_monthly_salary',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_expiry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
